%% Plot properties
PropName    = {'Color','Linestyle','Linewidth','Marker'};
PropValues  = { 'b', '-', 1.5, 'o'; ...
                'r', '-', 1.5, 's'; ...
                'k', ':', 1.5, 'x'; ...
                'g', '-', 1.5, 'o'; ...
                'c', ':', 2, 's'; ...
                'b', ':', 2, 's'; ...
                'k', ':', 2, 'x'; ...
                'g', ':', 2, 'o'};
